Decouple databroker search and summary UI from bluesky-browser
Xi-CAM/Xi-cam.gui pull request #34
Opened 2019-11-21 23:31 UTC by dylanmcreynolds

2019-11-22 00:48 UTC, danielballan commented on xicam/gui/bluesky/top_utils.py
> +CONFIG_FILE_NAME = 'bluesky_browser_config.py'
This should probably be updated. In the future we can have a larger discussion about configuration management, not sure if that should hold up this PR.

2019-11-22 00:53 UTC, danielballan reviewed
Thanks for putting this together so quickly. I left some suggestions, just things we can rename and remove if we like. Nothing critical.

2019-11-22 00:53 UTC, danielballan commented on xicam/gui/bluesky/top_utils.py
> +CONFIG_FILE_NAME = 'bluesky_browser_config.py'
This should probably be updated. In the future we can have a larger discussion about configuration management, not sure if that should hold up this PR.

2019-11-22 00:53 UTC, danielballan commented on xicam/gui/bluesky/search.py
> +log = logging.getLogger('bluesky_browser')
This should probably be changed to `'search_widget'` or, if Xi-cam already has a convention for logging scope, `'SOMETHING.search_widget'`.

2019-11-22 00:53 UTC, danielballan commented on setup.py
> +    install_requires=["qtpy", "pathlib", "pyqtgraph", "qdarkstyle", "qtmodern", "qtconsole", "xicam.plugins", "xicam.core"]
:tada:

2019-11-22 00:53 UTC, danielballan commented on xicam/gui/bluesky/utils.py
> +ConfigurableQTabWidget = MetaQObjectHasTraits(
This is no longer used.

2019-11-22 00:53 UTC, danielballan commented on xicam/gui/bluesky/utils.py
> +ConfigurableMoveableTabContainer = MetaQObjectHasTraits(
This is no longer used.

2019-11-22 00:53 UTC, danielballan commented on xicam/gui/bluesky/utils.py
> +class MoveableTabWidget(QTabWidget):
This is no longer used.

2019-11-22 00:53 UTC, danielballan commented on xicam/gui/bluesky/utils.py
> +class MoveableTabContainer(QWidget):
This is no longer used.

2019-11-22 14:26 UTC, danielballan requested changes
Consider #35 as an alternative way of getting to the same code.

2019-12-02 21:50 UTC, ronpandolfi commented
Closing in favor of https://github.com/synchrotrons/Xi-cam.gui/pull/35

2019-12-02 21:50 UTC, closed without merging